openapi: 3.1.0
info:
  version: 1.0.0
  title: WaterTracker Web App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |-
    **API documentation for project WaterTracker Web App**

    This project is a web application for tracking and managing water intake
      throughout the day. It calculates an individual daily water consumption
      rate based on user data and provides statistics for daily and monthly
      consumption. This helps users adjust their lifestyle and monitor progress
      toward better health.

    The project includes user registration, authentication, and authorization,
      with the ability to edit personal data and records. The application has a
      user-friendly interface, ensuring security through password encryption and
      token-based identification. Also application supports password recovery via email.

    **Key Features:**

    User registration and authorization.

    Update personal data, avatar, and password.

    Add, edit, and delete water intake records.

    Calculate and update daily water consumption rate.

    Display detailed daily and monthly water intake statistics.

    Password recovery via email.

    **Technology stack used in the project:**

    Node.js - JavaScript server runtime

    Express.js - framework for developing web applications on Node.js

    MongoDB - NoSQL Database

    Mongoose - library for working with MongoDB in Node.js

  contact:
    email: annasamtash@gmail.com
tags:
  - name: Auth
    description: Auth operations.
  - name: Users
    description: Operations about users.
  - name: WaterRate
    description: Operations about waterRate.
  - name: Water
    description: Operations about water record.
servers:
  - url: https://watertracker-app.onrender.com
paths:
  /water:
    post:
      $ref: ../swagger/paths/water/postWater.yaml
  /water/{id}:
    delete:
      $ref: ../swagger/paths/water/{id}/deleteWater.yaml
    patch:
      $ref: ../swagger/paths/water/{id}/patchWater.yaml
  /water/today:
    get:
      $ref: ../swagger/paths/water/getTodayWater.yaml
  /water/{year}/{month}:
    get:
      $ref: ../swagger/paths/water/{year}/{month}/getMonthlyWater.yaml
  /auth/signup:
    post:
      $ref: ../swagger/paths/auth/signUp.yaml
  /auth/signin:
    post:
      $ref: ../swagger/paths/auth/signIn.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/forgot-password:
    post:
      $ref: ../swagger/paths/auth/resetEmail.yaml
  /auth/update-password:
    post:
      $ref: ../swagger/paths/auth/resetPassword.yaml
  /users:
    patch:
      $ref: ../swagger/paths/user/patchUser.yaml
  /users/avatar:
    patch:
      $ref: ../swagger/paths/user/patchAvatar.yaml
  /users/current:
    get:
      $ref: ../swagger/paths/user/currentUserInfo.yaml
  /waterRate:
    patch:
      $ref: ../swagger/paths/waterRate/patchWaterRate.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
